// Generated by SugarLisp v0.5.6
var fs = require('fs');
var walk = function(rootDir) {
  return fs.readdir(rootDir, function(err, files) {
    if (err) {
      console.error("a readdir error occurred:", err)
    } else {
      files.forEach(function(file) {
        var filePath = [rootDir, '/', file].join('');
        return fs.stat(filePath, function(err, stats) {
          if (err) {
            console.error("a stat error occurred:", err)
          } else {
            (stats.isDirectory() ?
              (console.log('directory:', filePath) || walk(filePath)) :
              (console.log(filePath) || true))
          };
        });
      })
    };
  });
};

walk('.');