// Generated by SugarLisp v0.5.6
var dnode = require('dnode');


var d = dnode.connect(5004);
return d.on('remote', function(remote) {
  return remote.transform('beep', function(err, s) {
    if (err) {
      console.error(['an error occurred: ', err].join(''))
    } else {
      console.log(['beep goes ', s].join(''));
      d.end();
    };
  });
});