// Generated by SugarLisp v0.6.5
exports["awaitgen"] = function(forms) {
  var macrodef = ["macro", ["result", "asynccall", "then", "error"],
    ["try-", ["var", ["~", "result"],
        ["yield", ["~", "asynccall"]]
      ],
      ["~", "then"],
      ["function", ["err"],
        ["~", "error"]
      ]
    ]
  ];
  return this.macroexpand(forms, macrodef);
};

exports["awaitgenPrior"] = function(forms) {
  var macrodef = ["macro", ["result", "asynccall", "then", "error"],
    ["iifegen", ["try*", ["var", ["~", "result"],
        ["yield", ["~", "asynccall"]]
      ],
      ["~", "then"],
      ["function", ["err"],
        ["~", "error"]
      ]
    ]]
  ];
  return this.macroexpand(forms, macrodef);
};
exports["asyncgen"] = function(forms) {
  var macrodef = ["macro", ["func", "...rest"],
    [
      [".", "co", "wrap"],
      ["function*", ["~", "rest"]]
    ]
  ];
  return this.macroexpand(forms, macrodef);
};

exports["iifegen"] = function(forms) {
  var macrodef = ["macro", ["iifewrapped"],
    [
      [
        [".", "co", "wrap"],
        ["~", "iifewrapped"]
      ]
    ]
  ];
  return this.macroexpand(forms, macrodef);
};