// Generated by SugarLisp v0.5.6
exports["awaitsync"] = function(forms) {
  var macrodef = ["macro", ["result", "asynccall", "then", "error"],
    ["try", ["var", ["~", "result"],
        ["~", ["js", "\"$args.asynccall[0].set($args.asynccall[0].toString() + 'Sync'); return $args.asynccall;\""]]
      ],
      ["~", "then"],
      ["function", ["err"],
        ["~", "error"]
      ]
    ]
  ];
  return this.macroexpand(forms, macrodef);
};
exports["sync"] = function(forms) {
  var macrodef = ["macro", ["func", "...rest"],
    ["function", ["~", "rest"]]
  ];
  return this.macroexpand(forms, macrodef);
};